type MessageType = "image" | "video" | "doc" | "text";
type MessageSender = "customer" | "agent" | "ai";

interface ChatMessage {
  id: string;
  type: MessageType;
  sender: MessageSender;
  content: string;
  read: boolean;
  createdAt: string;
}

export interface ChatType {
  id: string;
  customer: string;
  isOnline: boolean;
  nbUnreadMessage: number;
  lastMessageText: string;
  lastMessageType: MessageType;
  lastMessageAt: string;
  messages: ChatMessage[];
}

/**
 * Données pour les conversations
 */
export const chats: ChatType[] = [
  {
    id: "chat_001",
    customer: "Marie Dubois",
    isOnline: true,
    nbUnreadMessage: 3,
    lastMessageText: "Merci beaucoup pour votre aide !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T14:32:15Z",
    messages: [
      {
        id: "msg_001_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, j'ai un problème avec ma commande #12345",
        read: true,
        createdAt: "2026-01-30T10:15:00Z",
      },
      {
        id: "msg_001_02",
        type: "text",
        sender: "agent",
        content:
          "Bonjour Marie ! Je vais vous aider. Quel est le problème exactement ?",
        read: true,
        createdAt: "2026-01-30T10:16:30Z",
      },
      {
        id: "msg_001_03",
        type: "text",
        sender: "customer",
        content:
          "Je n'ai pas reçu l'article que j'ai commandé il y a 2 semaines",
        read: true,
        createdAt: "2026-01-30T10:17:45Z",
      },
      {
        id: "msg_001_04",
        type: "text",
        sender: "agent",
        content:
          "Je comprends votre inquiétude. Laissez-moi vérifier le statut de votre commande.",
        read: true,
        createdAt: "2026-01-30T10:18:20Z",
      },

      {
        id: "msg_001_06",
        type: "text",
        sender: "agent",
        content:
          "Merci pour la capture d'écran. Je vois que votre colis est en transit depuis 5 jours.",
        read: true,
        createdAt: "2026-01-30T10:21:00Z",
      },
      {
        id: "msg_001_07",
        type: "text",
        sender: "customer",
        content: "Est-ce normal que ça prenne autant de temps ?",
        read: true,
        createdAt: "2026-01-30T10:22:30Z",
      },
      {
        id: "msg_001_08",
        type: "text",
        sender: "ai",
        content:
          "Les délais de livraison peuvent varier selon votre région. Le délai standard est de 5 à 10 jours ouvrés.",
        read: true,
        createdAt: "2026-01-30T10:23:15Z",
      },
      {
        id: "msg_001_09",
        type: "text",
        sender: "agent",
        content:
          "Exactement. Votre colis devrait arriver d'ici 3 jours maximum.",
        read: true,
        createdAt: "2026-01-30T10:24:00Z",
      },

      {
        id: "msg_001_11",
        type: "text",
        sender: "customer",
        content: "D'accord, je vais attendre encore un peu alors",
        read: true,
        createdAt: "2026-01-30T10:27:00Z",
      },
      {
        id: "msg_001_12",
        type: "text",
        sender: "agent",
        content:
          "Parfait ! Si vous n'avez rien reçu d'ici lundi, contactez-nous à nouveau.",
        read: true,
        createdAt: "2026-01-30T10:28:30Z",
      },
      {
        id: "msg_001_13",
        type: "text",
        sender: "customer",
        content: "Entendu. Vous pouvez me donner le numéro de suivi ?",
        read: true,
        createdAt: "2026-01-30T10:30:15Z",
      },
      {
        id: "msg_001_14",
        type: "text",
        sender: "agent",
        content: "Bien sûr ! Votre numéro de suivi est : FR789456123",
        read: true,
        createdAt: "2026-01-30T10:31:00Z",
      },
      {
        id: "msg_001_15",
        type: "text",
        sender: "customer",
        content: "Super, merci !",
        read: true,
        createdAt: "2026-01-30T10:32:20Z",
      },
      {
        id: "msg_001_16",
        type: "text",
        sender: "agent",
        content: "De rien ! Puis-je vous aider avec autre chose aujourd'hui ?",
        read: true,
        createdAt: "2026-01-30T10:33:45Z",
      },
      {
        id: "msg_001_17",
        type: "text",
        sender: "customer",
        content: "Non, c'est tout pour le moment",
        read: true,
        createdAt: "2026-01-30T14:30:00Z",
      },
      {
        id: "msg_001_18",
        type: "text",
        sender: "agent",
        content: "Très bien ! N'hésitez pas à nous contacter si besoin.",
        read: true,
        createdAt: "2026-01-30T14:31:15Z",
      },
      {
        id: "msg_001_19",
        type: "text",
        sender: "customer",
        content: "Merci beaucoup pour votre aide !",
        read: false,
        createdAt: "2026-01-30T14:32:15Z",
      },
      {
        id: "msg_001_20",
        type: "text",
        sender: "agent",
        content: "Avec plaisir ! Bonne journée Marie",
        read: false,
        createdAt: "2026-01-30T14:32:50Z",
      },
    ],
  },
  {
    id: "chat_002",
    customer: "Jean Martin",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Parfait, merci pour la résolution rapide !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T11:45:30Z",
    messages: [
      {
        id: "msg_002_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, mon compte ne fonctionne plus",
        read: true,
        createdAt: "2026-01-30T09:00:00Z",
      },
      {
        id: "msg_002_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour ! Je peux vous aider avec votre compte. Quel message d'erreur voyez-vous ?",
        read: true,
        createdAt: "2026-01-30T09:01:00Z",
      },
      {
        id: "msg_002_03",
        type: "text",
        sender: "customer",
        content: "Il affiche 'compte temporairement suspendu'",
        read: true,
        createdAt: "2026-01-30T09:02:30Z",
      },

      {
        id: "msg_002_05",
        type: "text",
        sender: "agent",
        content:
          "Bonjour Jean, je prends le relais. Laissez-moi examiner votre compte.",
        read: true,
        createdAt: "2026-01-30T09:05:00Z",
      },
      {
        id: "msg_002_06",
        type: "text",
        sender: "customer",
        content: "D'accord, merci",
        read: true,
        createdAt: "2026-01-30T09:06:00Z",
      },
      {
        id: "msg_002_07",
        type: "text",
        sender: "agent",
        content:
          "Je vois le problème. Votre compte a été suspendu pour activité inhabituelle détectée hier soir.",
        read: true,
        createdAt: "2026-01-30T09:08:30Z",
      },
      {
        id: "msg_002_08",
        type: "text",
        sender: "customer",
        content: "Activité inhabituelle ? Je n'ai rien fait de spécial",
        read: true,
        createdAt: "2026-01-30T09:09:45Z",
      },
      {
        id: "msg_002_09",
        type: "text",
        sender: "agent",
        content:
          "Notre système a détecté plusieurs tentatives de connexion depuis différents pays.",
        read: true,
        createdAt: "2026-01-30T09:11:00Z",
      },
      {
        id: "msg_002_10",
        type: "text",
        sender: "customer",
        content: "Oh non ! Mon compte a été piraté ?",
        read: true,
        createdAt: "2026-01-30T09:12:15Z",
      },
      {
        id: "msg_002_11",
        type: "text",
        sender: "agent",
        content:
          "C'est possible. Pour votre sécurité, je vais réinitialiser votre mot de passe.",
        read: true,
        createdAt: "2026-01-30T09:13:30Z",
      },
      {
        id: "msg_002_12",
        type: "text",
        sender: "customer",
        content: "Oui s'il vous plaît, faites ça rapidement",
        read: true,
        createdAt: "2026-01-30T09:14:00Z",
      },

      {
        id: "msg_002_14",
        type: "text",
        sender: "agent",
        content:
          "Voici un guide pour sécuriser votre compte. Je vous envoie aussi un lien de réinitialisation par email.",
        read: true,
        createdAt: "2026-01-30T09:17:30Z",
      },
      {
        id: "msg_002_15",
        type: "text",
        sender: "customer",
        content: "J'ai reçu l'email, merci !",
        read: true,
        createdAt: "2026-01-30T09:20:00Z",
      },
      {
        id: "msg_002_16",
        type: "text",
        sender: "agent",
        content:
          "Parfait ! N'oubliez pas d'activer l'authentification à deux facteurs.",
        read: true,
        createdAt: "2026-01-30T09:21:15Z",
      },
      {
        id: "msg_002_17",
        type: "text",
        sender: "customer",
        content: "Comment je fais ça ?",
        read: true,
        createdAt: "2026-01-30T09:22:30Z",
      },

      {
        id: "msg_002_19",
        type: "text",
        sender: "agent",
        content: "Voici un tutoriel vidéo qui vous explique tout pas à pas.",
        read: true,
        createdAt: "2026-01-30T09:24:30Z",
      },
      {
        id: "msg_002_20",
        type: "text",
        sender: "customer",
        content: "Parfait, merci pour la résolution rapide !",
        read: true,
        createdAt: "2026-01-30T11:45:30Z",
      },
    ],
  },
  {
    id: "chat_003",
    customer: "Sophie Laurent",
    isOnline: true,
    nbUnreadMessage: 5,
    lastMessageText: "Je vais essayer ça tout de suite",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T15:22:10Z",
    messages: [
      {
        id: "msg_003_01",
        type: "text",
        sender: "customer",
        content: "Aide ! L'application plante sans arrêt",
        read: true,
        createdAt: "2026-01-30T14:00:00Z",
      },
      {
        id: "msg_003_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Sophie ! Désolé pour ce désagrément. Sur quel appareil utilisez-vous l'application ?",
        read: true,
        createdAt: "2026-01-30T14:01:00Z",
      },
      {
        id: "msg_003_03",
        type: "text",
        sender: "customer",
        content: "iPhone 14, iOS 17.2",
        read: true,
        createdAt: "2026-01-30T14:02:15Z",
      },
      {
        id: "msg_003_04",
        type: "text",
        sender: "ai",
        content:
          "Merci pour cette information. Avez-vous la dernière version de l'application ?",
        read: true,
        createdAt: "2026-01-30T14:03:00Z",
      },
      {
        id: "msg_003_05",
        type: "text",
        sender: "customer",
        content: "Je ne sais pas, comment je vérifie ?",
        read: true,
        createdAt: "2026-01-30T14:04:30Z",
      },

      {
        id: "msg_003_07",
        type: "text",
        sender: "ai",
        content:
          "Allez dans l'App Store, recherchez notre app et vérifiez s'il y a un bouton 'Mettre à jour'.",
        read: true,
        createdAt: "2026-01-30T14:06:00Z",
      },
      {
        id: "msg_003_08",
        type: "text",
        sender: "customer",
        content: "Ah oui ! Il y a une mise à jour disponible",
        read: true,
        createdAt: "2026-01-30T14:08:00Z",
      },
      {
        id: "msg_003_09",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Je prends le relais. Installez la mise à jour, elle corrige justement ce bug.",
        read: true,
        createdAt: "2026-01-30T14:10:00Z",
      },
      {
        id: "msg_003_10",
        type: "text",
        sender: "customer",
        content: "Ok, ça télécharge... C'est long !",
        read: true,
        createdAt: "2026-01-30T14:12:30Z",
      },
      {
        id: "msg_003_11",
        type: "text",
        sender: "agent",
        content:
          "La mise à jour fait 250 Mo, ça peut prendre quelques minutes selon votre connexion.",
        read: true,
        createdAt: "2026-01-30T14:13:45Z",
      },
      {
        id: "msg_003_12",
        type: "text",
        sender: "customer",
        content:
          "D'accord. Pendant ce temps, puis-je poser une autre question ?",
        read: true,
        createdAt: "2026-01-30T14:15:00Z",
      },
      {
        id: "msg_003_13",
        type: "text",
        sender: "agent",
        content: "Bien sûr ! Je vous écoute.",
        read: true,
        createdAt: "2026-01-30T14:15:30Z",
      },
      {
        id: "msg_003_14",
        type: "text",
        sender: "customer",
        content: "Comment je peux exporter mes données ?",
        read: true,
        createdAt: "2026-01-30T14:16:45Z",
      },

      {
        id: "msg_003_16",
        type: "text",
        sender: "agent",
        content:
          "Voici un tutoriel vidéo. Vous trouverez l'option dans Paramètres > Mes données > Exporter.",
        read: true,
        createdAt: "2026-01-30T14:18:30Z",
      },

      {
        id: "msg_003_18",
        type: "text",
        sender: "agent",
        content: "Et voici aussi un guide PDF détaillé si vous préférez lire.",
        read: true,
        createdAt: "2026-01-30T14:19:30Z",
      },
      {
        id: "msg_003_19",
        type: "text",
        sender: "customer",
        content: "Super ! La mise à jour est terminée maintenant",
        read: false,
        createdAt: "2026-01-30T15:21:00Z",
      },
      {
        id: "msg_003_20",
        type: "text",
        sender: "customer",
        content: "Je vais essayer ça tout de suite",
        read: false,
        createdAt: "2026-01-30T15:22:10Z",
      },
    ],
  },
  {
    id: "chat_004",
    customer: "Pierre Rousseau",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Merci, bonne soirée !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T18:30:45Z",
    messages: [
      {
        id: "msg_004_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, je voudrais annuler mon abonnement",
        read: true,
        createdAt: "2026-01-30T16:00:00Z",
      },
      {
        id: "msg_004_02",
        type: "text",
        sender: "agent",
        content:
          "Bonjour Pierre. Je suis désolé d'apprendre que vous souhaitez partir. Puis-je savoir pourquoi ?",
        read: true,
        createdAt: "2026-01-30T16:01:30Z",
      },
      {
        id: "msg_004_03",
        type: "text",
        sender: "customer",
        content: "C'est trop cher pour ce que j'utilise réellement",
        read: true,
        createdAt: "2026-01-30T16:03:00Z",
      },
      {
        id: "msg_004_04",
        type: "text",
        sender: "agent",
        content:
          "Je comprends tout à fait. Savez-vous que nous avons des forfaits plus économiques ?",
        read: true,
        createdAt: "2026-01-30T16:04:15Z",
      },
      {
        id: "msg_004_05",
        type: "text",
        sender: "customer",
        content: "Non, je ne savais pas. Quelles sont les options ?",
        read: true,
        createdAt: "2026-01-30T16:05:30Z",
      },

      {
        id: "msg_004_07",
        type: "text",
        sender: "agent",
        content:
          "Voici nos différents forfaits. Vous êtes actuellement sur le Premium à 29,99€/mois.",
        read: true,
        createdAt: "2026-01-30T16:07:00Z",
      },
      {
        id: "msg_004_08",
        type: "text",
        sender: "customer",
        content:
          "Je vois qu'il y a un forfait Basique à 9,99€. Qu'est-ce que je perds ?",
        read: true,
        createdAt: "2026-01-30T16:09:00Z",
      },
      {
        id: "msg_004_09",
        type: "text",
        sender: "agent",
        content:
          "Vous perdez l'accès aux fonctionnalités avancées et le stockage illimité. Mais les fonctions de base restent.",
        read: true,
        createdAt: "2026-01-30T16:10:30Z",
      },
      {
        id: "msg_004_10",
        type: "text",
        sender: "customer",
        content:
          "Hmm, je n'utilise jamais les fonctions avancées de toute façon",
        read: true,
        createdAt: "2026-01-30T16:12:00Z",
      },
      {
        id: "msg_004_11",
        type: "text",
        sender: "agent",
        content:
          "Dans ce cas, le forfait Basique serait parfait pour vous ! Voulez-vous que je fasse le changement ?",
        read: true,
        createdAt: "2026-01-30T16:13:15Z",
      },
      {
        id: "msg_004_12",
        type: "text",
        sender: "customer",
        content: "Oui, s'il vous plaît. À partir de quand ?",
        read: true,
        createdAt: "2026-01-30T16:14:30Z",
      },
      {
        id: "msg_004_13",
        type: "text",
        sender: "agent",
        content:
          "Le changement sera effectif à partir de votre prochaine date de facturation, le 15 février.",
        read: true,
        createdAt: "2026-01-30T16:15:45Z",
      },
      {
        id: "msg_004_14",
        type: "text",
        sender: "customer",
        content:
          "Parfait ! Je garde donc tous mes avantages jusqu'au 15 février ?",
        read: true,
        createdAt: "2026-01-30T16:17:00Z",
      },
      {
        id: "msg_004_15",
        type: "text",
        sender: "agent",
        content:
          "Exactement ! Vous profitez de votre forfait Premium actuel jusqu'à cette date.",
        read: true,
        createdAt: "2026-01-30T16:18:15Z",
      },
      {
        id: "msg_004_16",
        type: "text",
        sender: "customer",
        content: "Excellent, merci pour cette solution !",
        read: true,
        createdAt: "2026-01-30T16:19:30Z",
      },
      {
        id: "msg_004_17",
        type: "text",
        sender: "agent",
        content:
          "Avec plaisir ! Je suis content qu'on ait pu trouver une solution qui vous convient.",
        read: true,
        createdAt: "2026-01-30T18:28:00Z",
      },
      {
        id: "msg_004_18",
        type: "text",
        sender: "agent",
        content:
          "Vous recevrez un email de confirmation dans quelques minutes.",
        read: true,
        createdAt: "2026-01-30T18:29:15Z",
      },
      {
        id: "msg_004_19",
        type: "text",
        sender: "customer",
        content: "Super, je vais vérifier",
        read: true,
        createdAt: "2026-01-30T18:30:00Z",
      },
      {
        id: "msg_004_20",
        type: "text",
        sender: "customer",
        content: "Merci, bonne soirée !",
        read: true,
        createdAt: "2026-01-30T18:30:45Z",
      },
    ],
  },
  {
    id: "chat_006",
    customer: "Thomas Petit",
    isOnline: true,
    nbUnreadMessage: 1,
    lastMessageText: "Voici la vidéo du problème",
    lastMessageType: "video",
    lastMessageAt: "2026-01-30T16:45:00Z",
    messages: [
      {
        id: "msg_006_01",
        type: "text",
        sender: "customer",
        content: "Le paiement ne passe pas, j'ai essayé 3 fois !",
        read: true,
        createdAt: "2026-01-30T15:30:00Z",
      },
      {
        id: "msg_006_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Thomas ! Je suis désolé pour ce problème. Quel message d'erreur recevez-vous ?",
        read: true,
        createdAt: "2026-01-30T15:31:00Z",
      },
      {
        id: "msg_006_03",
        type: "text",
        sender: "customer",
        content: "Transaction refusée, contactez votre banque",
        read: true,
        createdAt: "2026-01-30T15:32:30Z",
      },
      {
        id: "msg_006_04",
        type: "text",
        sender: "ai",
        content:
          "Ce message vient généralement de votre banque. Avez-vous vérifié avec eux ?",
        read: true,
        createdAt: "2026-01-30T15:33:45Z",
      },
      {
        id: "msg_006_05",
        type: "text",
        sender: "customer",
        content: "Oui, ils disent que tout est ok de leur côté",
        read: true,
        createdAt: "2026-01-30T15:35:00Z",
      },
      {
        id: "msg_006_06",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Je reprends votre demande. Avez-vous suffisamment de fonds sur votre compte ?",
        read: true,
        createdAt: "2026-01-30T15:37:00Z",
      },
      {
        id: "msg_006_07",
        type: "text",
        sender: "customer",
        content: "Oui, largement ! C'est vraiment frustrant",
        read: true,
        createdAt: "2026-01-30T15:38:15Z",
      },
      {
        id: "msg_006_08",
        type: "text",
        sender: "agent",
        content:
          "Je comprends votre frustration. Essayez avec une autre carte de paiement si possible ?",
        read: true,
        createdAt: "2026-01-30T15:39:30Z",
      },
      {
        id: "msg_006_09",
        type: "text",
        sender: "customer",
        content:
          "J'ai essayé avec ma carte Visa et ma Mastercard, même problème",
        read: true,
        createdAt: "2026-01-30T15:41:00Z",
      },
      {
        id: "msg_006_10",
        type: "text",
        sender: "agent",
        content:
          "C'est étrange. Pouvez-vous me faire une capture d'écran du message d'erreur ?",
        read: true,
        createdAt: "2026-01-30T15:42:15Z",
      },

      {
        id: "msg_006_12",
        type: "text",
        sender: "agent",
        content:
          "Merci. Je vois le problème. Votre adresse de facturation ne correspond pas à celle de votre carte.",
        read: true,
        createdAt: "2026-01-30T15:45:00Z",
      },
      {
        id: "msg_006_13",
        type: "text",
        sender: "customer",
        content: "Ah ! J'ai déménagé le mois dernier",
        read: true,
        createdAt: "2026-01-30T15:46:30Z",
      },
      {
        id: "msg_006_14",
        type: "text",
        sender: "agent",
        content:
          "Voilà le problème ! Mettez à jour votre adresse dans votre profil et réessayez.",
        read: true,
        createdAt: "2026-01-30T15:47:45Z",
      },
      {
        id: "msg_006_15",
        type: "text",
        sender: "customer",
        content: "Comment je fais ça ?",
        read: true,
        createdAt: "2026-01-30T15:49:00Z",
      },

      {
        id: "msg_006_17",
        type: "text",
        sender: "agent",
        content:
          "Voici un tutoriel vidéo. Allez dans Paramètres > Mon profil > Adresse de facturation.",
        read: true,
        createdAt: "2026-01-30T15:51:00Z",
      },
      {
        id: "msg_006_18",
        type: "text",
        sender: "customer",
        content: "Ok je fais ça maintenant",
        read: true,
        createdAt: "2026-01-30T16:40:00Z",
      },
      {
        id: "msg_006_19",
        type: "text",
        sender: "customer",
        content: "Attendez, l'app crash quand j'essaie de modifier",
        read: true,
        createdAt: "2026-01-30T16:43:30Z",
      },
    ],
  },
  {
    id: "chat_007",
    customer: "Lucie Moreau",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Vous êtes au top, merci !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T12:30:00Z",
    messages: [
      {
        id: "msg_007_01",
        type: "text",
        sender: "customer",
        content: "Bonjour ! Je cherche un produit spécifique",
        read: true,
        createdAt: "2026-01-30T11:00:00Z",
      },
      {
        id: "msg_007_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Lucie ! Je suis là pour vous aider. Que cherchez-vous exactement ?",
        read: true,
        createdAt: "2026-01-30T11:01:00Z",
      },
      {
        id: "msg_007_03",
        type: "text",
        sender: "customer",
        content: "Un casque Bluetooth avec réduction de bruit active",
        read: true,
        createdAt: "2026-01-30T11:02:15Z",
      },
      {
        id: "msg_007_04",
        type: "text",
        sender: "ai",
        content: "Excellent choix ! Quel est votre budget approximatif ?",
        read: true,
        createdAt: "2026-01-30T11:03:00Z",
      },
      {
        id: "msg_007_05",
        type: "text",
        sender: "customer",
        content: "Entre 150 et 250 euros maximum",
        read: true,
        createdAt: "2026-01-30T11:04:30Z",
      },
      {
        id: "msg_007_06",
        type: "text",
        sender: "ai",
        content:
          "Parfait ! Je peux vous proposer 3 modèles dans cette gamme de prix.",
        read: true,
        createdAt: "2026-01-30T11:05:45Z",
      },

      {
        id: "msg_007_08",
        type: "text",
        sender: "ai",
        content:
          "Le Sony WH-1000XM4 à 229€ - excellente réduction de bruit, autonomie 30h",
        read: true,
        createdAt: "2026-01-30T11:07:00Z",
      },

      {
        id: "msg_007_10",
        type: "text",
        sender: "ai",
        content:
          "Le Bose QuietComfort 45 à 249€ - confort optimal, son équilibré",
        read: true,
        createdAt: "2026-01-30T11:08:15Z",
      },

      {
        id: "msg_007_12",
        type: "text",
        sender: "ai",
        content:
          "Le Sennheiser Momentum 4 à 199€ - excellent rapport qualité/prix, autonomie 60h",
        read: true,
        createdAt: "2026-01-30T11:09:30Z",
      },
      {
        id: "msg_007_13",
        type: "text",
        sender: "customer",
        content: "Wow, merci ! Le Sennheiser m'intéresse. Il est en stock ?",
        read: true,
        createdAt: "2026-01-30T11:11:00Z",
      },
      {
        id: "msg_007_14",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Oui, le Sennheiser Momentum 4 est disponible en noir et en blanc.",
        read: true,
        createdAt: "2026-01-30T11:12:30Z",
      },
      {
        id: "msg_007_15",
        type: "text",
        sender: "customer",
        content: "Je le veux en blanc ! Livraison rapide possible ?",
        read: true,
        createdAt: "2026-01-30T11:13:45Z",
      },
      {
        id: "msg_007_16",
        type: "text",
        sender: "agent",
        content:
          "Oui ! Livraison express en 24h pour 9,90€ ou standard gratuite en 3-5 jours.",
        read: true,
        createdAt: "2026-01-30T11:15:00Z",
      },
      {
        id: "msg_007_17",
        type: "text",
        sender: "customer",
        content: "Je prends la livraison express. Comment je commande ?",
        read: true,
        createdAt: "2026-01-30T11:16:30Z",
      },
      {
        id: "msg_007_18",
        type: "text",
        sender: "agent",
        content:
          "Je vous envoie le lien direct vers le produit avec le code promo FAST24 pour -10€ sur l'express.",
        read: true,
        createdAt: "2026-01-30T11:18:00Z",
      },
      {
        id: "msg_007_19",
        type: "text",
        sender: "customer",
        content: "Super ! Commande passée, merci pour le code promo",
        read: true,
        createdAt: "2026-01-30T12:28:00Z",
      },
      {
        id: "msg_007_20",
        type: "text",
        sender: "customer",
        content: "Vous êtes au top, merci !",
        read: true,
        createdAt: "2026-01-30T12:30:00Z",
      },
    ],
  },
  {
    id: "chat_008",
    customer: "Nicolas Girard",
    isOnline: true,
    nbUnreadMessage: 4,
    lastMessageText: "C'est urgent, j'ai besoin de mes données maintenant j'ai besoin de mes données maintenant ",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T17:15:30Z",
    messages: [
      {
        id: "msg_008_01",
        type: "text",
        sender: "customer",
        content: "URGENT : J'ai perdu toutes mes données !",
        read: true,
        createdAt: "2026-01-30T16:50:00Z",
      },
      {
        id: "msg_008_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Nicolas, je comprends votre urgence. Que s'est-il passé exactement ?",
        read: true,
        createdAt: "2026-01-30T16:51:00Z",
      },
      {
        id: "msg_008_03",
        type: "text",
        sender: "customer",
        content: "J'ai supprimé mon compte par erreur",
        read: true,
        createdAt: "2026-01-30T16:52:15Z",
      },
      {
        id: "msg_008_04",
        type: "text",
        sender: "ai",
        content:
          "Ne vous inquiétez pas ! Il y a une période de grâce de 30 jours. Vos données sont encore récupérables.",
        read: true,
        createdAt: "2026-01-30T16:53:30Z",
      },
      {
        id: "msg_008_05",
        type: "text",
        sender: "customer",
        content: "Ah ouf ! Comment je récupère tout ?",
        read: true,
        createdAt: "2026-01-30T16:54:45Z",
      },
      {
        id: "msg_008_06",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Je m'occupe de votre cas personnellement. Quelle est votre adresse email ?",
        read: true,
        createdAt: "2026-01-30T16:56:00Z",
      },
      {
        id: "msg_008_07",
        type: "text",
        sender: "customer",
        content: "nicolas.girard@email.com",
        read: true,
        createdAt: "2026-01-30T16:57:15Z",
      },
      {
        id: "msg_008_08",
        type: "text",
        sender: "agent",
        content:
          "Merci. Je vérifie votre compte... Oui, je vois la suppression du 30/01 à 16h45.",
        read: true,
        createdAt: "2026-01-30T16:59:00Z",
      },
      {
        id: "msg_008_09",
        type: "text",
        sender: "customer",
        content: "Oui c'est ça ! Vous pouvez restaurer ?",
        read: true,
        createdAt: "2026-01-30T17:00:30Z",
      },
      {
        id: "msg_008_10",
        type: "text",
        sender: "agent",
        content:
          "Absolument. Je lance la procédure de restauration. Cela prendra environ 15 minutes.",
        read: true,
        createdAt: "2026-01-30T17:01:45Z",
      },
      {
        id: "msg_008_11",
        type: "text",
        sender: "customer",
        content: "15 minutes ?! C'est trop long !",
        read: true,
        createdAt: "2026-01-30T17:03:00Z",
      },
      {
        id: "msg_008_12",
        type: "text",
        sender: "agent",
        content:
          "C'est le temps nécessaire pour restaurer toutes vos données en toute sécurité.",
        read: true,
        createdAt: "2026-01-30T17:04:15Z",
      },

      {
        id: "msg_008_14",
        type: "text",
        sender: "agent",
        content:
          "Voici le document qui explique le processus de restauration détaillé.",
        read: true,
        createdAt: "2026-01-30T17:06:00Z",
      },
      {
        id: "msg_008_15",
        type: "text",
        sender: "customer",
        content: "Ok ok... Je peux faire quoi en attendant ?",
        read: true,
        createdAt: "2026-01-30T17:07:30Z",
      },
      {
        id: "msg_008_16",
        type: "text",
        sender: "agent",
        content:
          "Restez connecté sur cette conversation, je vous tiendrai informé de la progression.",
        read: true,
        createdAt: "2026-01-30T17:09:00Z",
      },
      {
        id: "msg_008_17",
        type: "text",
        sender: "customer",
        content: "Ça fait déjà 5 minutes, où en est-on ?",
        read: false,
        createdAt: "2026-01-30T17:12:15Z",
      },
      {
        id: "msg_008_18",
        type: "text",
        sender: "customer",
        content: "Vous êtes toujours là ?",
        read: false,
        createdAt: "2026-01-30T17:13:45Z",
      },

      {
        id: "msg_008_20",
        type: "text",
        sender: "customer",
        content: "C'est urgent, j'ai besoin de mes données maintenant",
        read: false,
        createdAt: "2026-01-30T17:15:30Z",
      },
    ],
  },
  {
    id: "chat_009",
    customer: "Camille Leroy",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Au revoir et merci encore !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T10:50:00Z",
    messages: [
      {
        id: "msg_009_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, comment changer mon mot de passe ?",
        read: true,
        createdAt: "2026-01-30T10:00:00Z",
      },
      {
        id: "msg_009_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Camille ! C'est très simple. Allez dans Paramètres > Sécurité > Mot de passe.",
        read: true,
        createdAt: "2026-01-30T10:01:00Z",
      },

      {
        id: "msg_009_04",
        type: "text",
        sender: "customer",
        content: "J'y suis. Et maintenant ?",
        read: true,
        createdAt: "2026-01-30T10:03:00Z",
      },
      {
        id: "msg_009_05",
        type: "text",
        sender: "ai",
        content:
          "Cliquez sur 'Modifier le mot de passe', entrez l'ancien puis le nouveau deux fois.",
        read: true,
        createdAt: "2026-01-30T10:04:15Z",
      },
      {
        id: "msg_009_06",
        type: "text",
        sender: "customer",
        content: "Il me demande l'ancien mais je ne m'en souviens plus...",
        read: true,
        createdAt: "2026-01-30T10:05:30Z",
      },
      {
        id: "msg_009_07",
        type: "text",
        sender: "ai",
        content:
          "Pas de problème ! Cliquez sur 'Mot de passe oublié' en dessous.",
        read: true,
        createdAt: "2026-01-30T10:06:45Z",
      },
      {
        id: "msg_009_08",
        type: "text",
        sender: "customer",
        content: "Ok fait ! J'ai reçu un email",
        read: true,
        createdAt: "2026-01-30T10:08:00Z",
      },
      {
        id: "msg_009_09",
        type: "text",
        sender: "ai",
        content:
          "Parfait ! Cliquez sur le lien dans l'email pour réinitialiser votre mot de passe.",
        read: true,
        createdAt: "2026-01-30T10:09:15Z",
      },
      {
        id: "msg_009_10",
        type: "text",
        sender: "customer",
        content: "Le lien ne fonctionne pas, il dit 'lien expiré'",
        read: true,
        createdAt: "2026-01-30T10:11:00Z",
      },
      {
        id: "msg_009_11",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Les liens expirent après 15 minutes. Je vous en renvoie un nouveau.",
        read: true,
        createdAt: "2026-01-30T10:13:00Z",
      },
      {
        id: "msg_009_12",
        type: "text",
        sender: "customer",
        content: "Merci ! Je viens de le recevoir",
        read: true,
        createdAt: "2026-01-30T10:14:30Z",
      },
      {
        id: "msg_009_13",
        type: "text",
        sender: "agent",
        content: "Super ! Cette fois vous avez 15 minutes pour l'utiliser.",
        read: true,
        createdAt: "2026-01-30T10:15:45Z",
      },
      {
        id: "msg_009_14",
        type: "text",
        sender: "customer",
        content: "Ça y est, j'ai changé mon mot de passe !",
        read: true,
        createdAt: "2026-01-30T10:18:00Z",
      },
      {
        id: "msg_009_15",
        type: "text",
        sender: "agent",
        content: "Excellent ! Notez-le dans un endroit sûr cette fois",
        read: true,
        createdAt: "2026-01-30T10:19:15Z",
      },
      {
        id: "msg_009_16",
        type: "text",
        sender: "customer",
        content: "Oui je vais faire ça ! Merci pour votre aide",
        read: true,
        createdAt: "2026-01-30T10:20:30Z",
      },
      {
        id: "msg_009_17",
        type: "text",
        sender: "agent",
        content:
          "Avec plaisir ! Je vous conseille aussi d'activer l'authentification à deux facteurs.",
        read: true,
        createdAt: "2026-01-30T10:21:45Z",
      },

      {
        id: "msg_009_19",
        type: "text",
        sender: "customer",
        content: "Ok je regarderai ça plus tard, merci !",
        read: true,
        createdAt: "2026-01-30T10:48:00Z",
      },
      {
        id: "msg_009_20",
        type: "text",
        sender: "customer",
        content: "Au revoir et merci encore !",
        read: true,
        createdAt: "2026-01-30T10:50:00Z",
      },
    ],
  },
  {
    id: "chat_011",
    customer: "Émilie Simon",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Parfait, tout est clair maintenant !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T09:45:30Z",
    messages: [
      {
        id: "msg_011_01",
        type: "text",
        sender: "customer",
        content: "Salut ! Question sur la politique de retour",
        read: true,
        createdAt: "2026-01-30T09:00:00Z",
      },
      {
        id: "msg_011_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Émilie ! Avec plaisir. Quelle est votre question exactement ?",
        read: true,
        createdAt: "2026-01-30T09:01:15Z",
      },
      {
        id: "msg_011_03",
        type: "text",
        sender: "customer",
        content:
          "J'ai acheté un article il y a 25 jours, je peux encore le retourner ?",
        read: true,
        createdAt: "2026-01-30T09:02:30Z",
      },
      {
        id: "msg_011_04",
        type: "text",
        sender: "ai",
        content:
          "Oui ! Notre politique de retour est de 30 jours. Vous avez encore 5 jours.",
        read: true,
        createdAt: "2026-01-30T09:03:45Z",
      },

      {
        id: "msg_011_06",
        type: "text",
        sender: "ai",
        content: "Voici notre politique complète de retour et remboursement.",
        read: true,
        createdAt: "2026-01-30T09:05:30Z",
      },
      {
        id: "msg_011_07",
        type: "text",
        sender: "customer",
        content: "Super ! Je dois payer les frais de retour ?",
        read: true,
        createdAt: "2026-01-30T09:07:00Z",
      },
      {
        id: "msg_011_08",
        type: "text",
        sender: "ai",
        content:
          "Non, les retours sont gratuits ! Nous vous envoyons une étiquette prépayée par email.",
        read: true,
        createdAt: "2026-01-30T09:08:15Z",
      },
      {
        id: "msg_011_09",
        type: "text",
        sender: "customer",
        content: "Cool ! Et je serai remboursée quand ?",
        read: true,
        createdAt: "2026-01-30T09:09:30Z",
      },
      {
        id: "msg_011_10",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Une fois que nous recevons l'article, le remboursement prend 3-5 jours ouvrés.",
        read: true,
        createdAt: "2026-01-30T09:11:00Z",
      },
      {
        id: "msg_011_11",
        type: "text",
        sender: "customer",
        content: "D'accord. Comment je demande l'étiquette de retour ?",
        read: true,
        createdAt: "2026-01-30T09:12:30Z",
      },
      {
        id: "msg_011_12",
        type: "text",
        sender: "agent",
        content:
          "Allez dans votre compte > Mes commandes > Sélectionnez l'article > Retourner cet article.",
        read: true,
        createdAt: "2026-01-30T09:14:00Z",
      },

      {
        id: "msg_011_14",
        type: "text",
        sender: "agent",
        content:
          "Voici une vidéo qui vous montre toute la procédure étape par étape.",
        read: true,
        createdAt: "2026-01-30T09:15:45Z",
      },
      {
        id: "msg_011_15",
        type: "text",
        sender: "customer",
        content: "Merci ! L'article doit être dans l'emballage d'origine ?",
        read: true,
        createdAt: "2026-01-30T09:17:00Z",
      },
      {
        id: "msg_011_16",
        type: "text",
        sender: "agent",
        content:
          "Idéalement oui, mais ce n'est pas obligatoire. L'important est que l'article soit en bon état.",
        read: true,
        createdAt: "2026-01-30T09:18:30Z",
      },
      {
        id: "msg_011_17",
        type: "text",
        sender: "customer",
        content:
          "Ok parfait. Et si je veux échanger au lieu de me faire rembourser ?",
        read: true,
        createdAt: "2026-01-30T09:20:00Z",
      },
      {
        id: "msg_011_18",
        type: "text",
        sender: "agent",
        content:
          "Pas de problème ! Sélectionnez simplement 'Échanger' au lieu de 'Retourner' et choisissez le nouvel article.",
        read: true,
        createdAt: "2026-01-30T09:21:30Z",
      },
      {
        id: "msg_011_19",
        type: "text",
        sender: "customer",
        content: "Génial ! Vous avez répondu à toutes mes questions",
        read: true,
        createdAt: "2026-01-30T09:44:00Z",
      },
      {
        id: "msg_011_20",
        type: "text",
        sender: "customer",
        content: "Parfait, tout est clair maintenant !",
        read: true,
        createdAt: "2026-01-30T09:45:30Z",
      },
    ],
  },
  {
    id: "chat_012",
    customer: "Alexandre Durand",
    isOnline: true,
    nbUnreadMessage: 7,
    lastMessageText: "JE VEUX UN REMBOURSEMENT COMPLET !!!",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T15:58:45Z",
    messages: [
      {
        id: "msg_012_01",
        type: "text",
        sender: "customer",
        content: "C'est une honte ! Le produit est cassé !",
        read: true,
        createdAt: "2026-01-30T15:30:00Z",
      },
      {
        id: "msg_012_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Alexandre, je suis vraiment désolé d'apprendre cela. Pouvez-vous me montrer le problème ?",
        read: true,
        createdAt: "2026-01-30T15:31:15Z",
      },

      {
        id: "msg_012_04",
        type: "text",
        sender: "customer",
        content: "REGARDEZ ! C'est inacceptable !",
        read: true,
        createdAt: "2026-01-30T15:33:00Z",
      },
      {
        id: "msg_012_05",
        type: "text",
        sender: "agent",
        content:
          "Bonjour, je comprends votre frustration. C'est effectivement un défaut de fabrication.",
        read: true,
        createdAt: "2026-01-30T15:35:00Z",
      },
      {
        id: "msg_012_06",
        type: "text",
        sender: "customer",
        content: "Et vous allez faire quoi maintenant ?!",
        read: true,
        createdAt: "2026-01-30T15:36:15Z",
      },
      {
        id: "msg_012_07",
        type: "text",
        sender: "agent",
        content:
          "Je vous propose deux options : un remplacement immédiat ou un remboursement complet.",
        read: true,
        createdAt: "2026-01-30T15:37:30Z",
      },
      {
        id: "msg_012_08",
        type: "text",
        sender: "customer",
        content: "Combien de temps pour le remplacement ?",
        read: true,
        createdAt: "2026-01-30T15:38:45Z",
      },
      {
        id: "msg_012_09",
        type: "text",
        sender: "agent",
        content:
          "Nous pouvons vous l'envoyer en express, livraison demain avant 12h, gratuitement bien sûr.",
        read: true,
        createdAt: "2026-01-30T15:40:00Z",
      },
      {
        id: "msg_012_10",
        type: "text",
        sender: "customer",
        content: "Et je fais quoi du produit cassé ?",
        read: true,
        createdAt: "2026-01-30T15:41:30Z",
      },
      {
        id: "msg_012_11",
        type: "text",
        sender: "agent",
        content:
          "Le livreur reprendra l'ancien produit lors de la livraison du nouveau. Tout est pris en charge.",
        read: true,
        createdAt: "2026-01-30T15:43:00Z",
      },
      {
        id: "msg_012_12",
        type: "text",
        sender: "customer",
        content: "Mouais... Et si le nouveau est cassé aussi ?",
        read: true,
        createdAt: "2026-01-30T15:44:30Z",
      },
      {
        id: "msg_012_13",
        type: "text",
        sender: "agent",
        content:
          "Je vous assure que nous vérifions chaque produit de remplacement avant envoi. C'est très rare.",
        read: true,
        createdAt: "2026-01-30T15:46:00Z",
      },
      {
        id: "msg_012_14",
        type: "text",
        sender: "customer",
        content: "Ça devrait pas arriver DU TOUT !",
        read: false,
        createdAt: "2026-01-30T15:52:00Z",
      },
      {
        id: "msg_012_15",
        type: "text",
        sender: "agent",
        content:
          "Vous avez absolument raison. Pour compenser ce désagrément, je vous offre un bon de 20€ sur votre prochaine commande.",
        read: false,
        createdAt: "2026-01-30T15:53:30Z",
      },
      {
        id: "msg_012_16",
        type: "text",
        sender: "customer",
        content: "20€ ?! C'est tout ?!",
        read: false,
        createdAt: "2026-01-30T15:54:45Z",
      },
      {
        id: "msg_012_17",
        type: "text",
        sender: "customer",
        content: "Le produit coûte 150€ !",
        read: false,
        createdAt: "2026-01-30T15:55:30Z",
      },
      {
        id: "msg_012_18",
        type: "text",
        sender: "customer",
        content: "C'est une blague ?",
        read: false,
        createdAt: "2026-01-30T15:56:45Z",
      },
      {
        id: "msg_012_19",
        type: "text",
        sender: "customer",
        content: "Vous vous moquez de moi là",
        read: false,
        createdAt: "2026-01-30T15:57:30Z",
      },
      {
        id: "msg_012_20",
        type: "text",
        sender: "customer",
        content: "JE VEUX UN REMBOURSEMENT COMPLET !!!",
        read: false,
        createdAt: "2026-01-30T15:58:45Z",
      },
    ],
  },
  {
    id: "chat_013",
    customer: "Julie Mercier",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Merci infiniment pour tout !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T13:20:00Z",
    messages: [
      {
        id: "msg_013_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, je cherche un cadeau pour ma mère",
        read: true,
        createdAt: "2026-01-30T12:00:00Z",
      },
      {
        id: "msg_013_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Julie ! Avec plaisir pour vous aider. Quel type de cadeau recherchez-vous ?",
        read: true,
        createdAt: "2026-01-30T12:01:15Z",
      },
      {
        id: "msg_013_03",
        type: "text",
        sender: "customer",
        content:
          "Quelque chose de pratique pour la cuisine, elle adore cuisiner",
        read: true,
        createdAt: "2026-01-30T12:02:30Z",
      },
      {
        id: "msg_013_04",
        type: "text",
        sender: "ai",
        content: "Super ! Quel est votre budget approximatif ?",
        read: true,
        createdAt: "2026-01-30T12:03:45Z",
      },
      {
        id: "msg_013_05",
        type: "text",
        sender: "customer",
        content: "Entre 50 et 100 euros",
        read: true,
        createdAt: "2026-01-30T12:05:00Z",
      },
      {
        id: "msg_013_06",
        type: "text",
        sender: "agent",
        content: "Bonjour ! J'ai quelques excellentes suggestions pour vous.",
        read: true,
        createdAt: "2026-01-30T12:07:00Z",
      },

      {
        id: "msg_013_08",
        type: "text",
        sender: "agent",
        content:
          "Un batteur électrique de qualité professionnelle à 79€. Très apprécié par nos clients.",
        read: true,
        createdAt: "2026-01-30T12:08:45Z",
      },

      {
        id: "msg_013_10",
        type: "text",
        sender: "agent",
        content:
          "Ou ce coffret de couteaux de chef japonais à 95€. Qualité exceptionnelle !",
        read: true,
        createdAt: "2026-01-30T12:10:00Z",
      },
      {
        id: "msg_013_11",
        type: "text",
        sender: "customer",
        content: "Oh le coffret de couteaux est magnifique ! Elle va adorer",
        read: true,
        createdAt: "2026-01-30T12:11:30Z",
      },
      {
        id: "msg_013_12",
        type: "text",
        sender: "agent",
        content: "Excellent choix ! C'est pour quelle occasion ?",
        read: true,
        createdAt: "2026-01-30T12:12:45Z",
      },
      {
        id: "msg_013_13",
        type: "text",
        sender: "customer",
        content: "Son anniversaire dans 5 jours",
        read: true,
        createdAt: "2026-01-30T12:14:00Z",
      },
      {
        id: "msg_013_14",
        type: "text",
        sender: "agent",
        content:
          "Parfait ! Nous avons un service d'emballage cadeau gratuit. Vous voulez en profiter ?",
        read: true,
        createdAt: "2026-01-30T12:15:15Z",
      },
      {
        id: "msg_013_15",
        type: "text",
        sender: "customer",
        content: "Oh oui ! C'est super ça !",
        read: true,
        createdAt: "2026-01-30T12:16:30Z",
      },
      {
        id: "msg_013_16",
        type: "text",
        sender: "agent",
        content:
          "Génial ! Je peux aussi ajouter une carte avec un message personnalisé si vous voulez.",
        read: true,
        createdAt: "2026-01-30T12:17:45Z",
      },
      {
        id: "msg_013_17",
        type: "text",
        sender: "customer",
        content: "Oui avec plaisir ! Je peux écrire quoi ?",
        read: true,
        createdAt: "2026-01-30T12:19:00Z",
      },
      {
        id: "msg_013_18",
        type: "text",
        sender: "agent",
        content: "Écrivez-moi votre message et je l'ajouterai à la carte.",
        read: true,
        createdAt: "2026-01-30T13:15:00Z",
      },
      {
        id: "msg_013_19",
        type: "text",
        sender: "customer",
        content:
          "Joyeux anniversaire Maman ! Pour que tu puisses continuer à nous régaler. Je t'aime",
        read: true,
        createdAt: "2026-01-30T13:17:30Z",
      },
      {
        id: "msg_013_20",
        type: "text",
        sender: "customer",
        content: "Merci infiniment pour tout !",
        read: true,
        createdAt: "2026-01-30T13:20:00Z",
      },
    ],
  },
  {
    id: "chat_015",
    customer: "Isabelle Faure",
    isOnline: false,
    nbUnreadMessage: 0,
    lastMessageText: "Vous êtes formidables, merci !",
    lastMessageType: "text",
    lastMessageAt: "2026-01-30T11:55:00Z",
    messages: [
      {
        id: "msg_015_01",
        type: "text",
        sender: "customer",
        content: "Bonjour, je voudrais modifier ma commande",
        read: true,
        createdAt: "2026-01-30T10:30:00Z",
      },
      {
        id: "msg_015_02",
        type: "text",
        sender: "ai",
        content:
          "Bonjour Isabelle ! Quelle modification souhaitez-vous apporter ?",
        read: true,
        createdAt: "2026-01-30T10:31:15Z",
      },
      {
        id: "msg_015_03",
        type: "text",
        sender: "customer",
        content: "Changer l'adresse de livraison, j'ai déménagé",
        read: true,
        createdAt: "2026-01-30T10:32:30Z",
      },
      {
        id: "msg_015_04",
        type: "text",
        sender: "ai",
        content: "Pas de problème. Quel est le numéro de votre commande ?",
        read: true,
        createdAt: "2026-01-30T10:33:45Z",
      },
      {
        id: "msg_015_05",
        type: "text",
        sender: "customer",
        content: "#78901",
        read: true,
        createdAt: "2026-01-30T10:35:00Z",
      },
      {
        id: "msg_015_06",
        type: "text",
        sender: "agent",
        content:
          "Bonjour ! Je vérifie... Votre commande n'a pas encore été expédiée, parfait !",
        read: true,
        createdAt: "2026-01-30T10:37:00Z",
      },
      {
        id: "msg_015_07",
        type: "text",
        sender: "customer",
        content: "Ouf ! Quelle est la nouvelle adresse que je dois donner ?",
        read: true,
        createdAt: "2026-01-30T10:38:15Z",
      },
      {
        id: "msg_015_08",
        type: "text",
        sender: "agent",
        content:
          "Donnez-moi votre nouvelle adresse complète avec le code postal.",
        read: true,
        createdAt: "2026-01-30T10:39:30Z",
      },
      {
        id: "msg_015_09",
        type: "text",
        sender: "customer",
        content: "15 rue des Lilas, 75015 Paris",
        read: true,
        createdAt: "2026-01-30T10:41:00Z",
      },
      {
        id: "msg_015_10",
        type: "text",
        sender: "agent",
        content:
          "Parfait ! J'ai mis à jour l'adresse. Votre commande sera livrée à cette nouvelle adresse.",
        read: true,
        createdAt: "2026-01-30T10:42:30Z",
      },

      {
        id: "msg_015_12",
        type: "text",
        sender: "agent",
        content: "Voici la confirmation de votre commande modifiée.",
        read: true,
        createdAt: "2026-01-30T10:44:30Z",
      },
      {
        id: "msg_015_13",
        type: "text",
        sender: "customer",
        content: "Merci beaucoup ! Livraison toujours prévue pour quand ?",
        read: true,
        createdAt: "2026-01-30T10:46:00Z",
      },
      {
        id: "msg_015_14",
        type: "text",
        sender: "agent",
        content:
          "Toujours le même délai : livraison prévue le 3 février entre 9h et 12h.",
        read: true,
        createdAt: "2026-01-30T10:47:15Z",
      },
      {
        id: "msg_015_15",
        type: "text",
        sender: "customer",
        content: "Parfait ! Je serai là à cette date",
        read: true,
        createdAt: "2026-01-30T10:48:30Z",
      },
      {
        id: "msg_015_16",
        type: "text",
        sender: "agent",
        content: "Excellent ! Vous recevrez un SMS la veille pour confirmer.",
        read: true,
        createdAt: "2026-01-30T10:49:45Z",
      },
      {
        id: "msg_015_17",
        type: "text",
        sender: "customer",
        content: "Super ! C'est vraiment un service impeccable",
        read: true,
        createdAt: "2026-01-30T11:50:00Z",
      },
      {
        id: "msg_015_18",
        type: "text",
        sender: "agent",
        content:
          "Merci beaucoup pour vos compliments ! C'est toujours un plaisir d'aider nos clients.",
        read: true,
        createdAt: "2026-01-30T11:51:30Z",
      },
      {
        id: "msg_015_19",
        type: "text",
        sender: "customer",
        content: "Bonne journée à vous !",
        read: true,
        createdAt: "2026-01-30T11:53:45Z",
      },
      {
        id: "msg_015_20",
        type: "text",
        sender: "customer",
        content: "Vous êtes formidables, merci !",
        read: true,
        createdAt: "2026-01-30T11:55:00Z",
      },
    ],
  },
];
