import { Client } from "@/types/clients.types";

export const clientsData: Client[] = [
  {
    id: "cli_001",
    fullName: "Jean Dupont",
    email: "jean.dupont@acme.com",
    phone: "+33 6 12 34 56 78",
    company: "ACME Corp",
    tags: ["premium", "b2b"],
    createdAt: "2024-11-10",
  },
  {
    id: "cli_002",
    fullName: "Sarah Martin",
    email: "sarah@startup.io",
    phone: null,
    company: "Startup.io",
    tags: ["trial"],
    createdAt: "2025-01-02",
  },
  {
    id: "cli_003",
    fullName: "Lucas Bernard",
    email: null,
    phone: "+33 7 98 76 54 32",
    company: "Bernard Consulting",
    tags: ["vip", "support-heavy"],
    createdAt: "2024-09-18",
  },
  {
    id: "cli_004",
    fullName: "Nina Rossi",
    email: "nina@fintech.app",
    phone: "+39 345 222 8899",
    company: "Fintech App",
    tags: ["b2c", "active"],
    createdAt: "2025-01-20",
  },
  {
    id: "cli_005",
    fullName: "Mohamed El Amrani",
    email: "m.elamrani@logistics.ma",
    phone: "+212 6 61 22 33 44",
    company: "Atlas Logistics",
    tags: ["b2b", "active"],
    createdAt: "2024-10-05",
  },
  {
    id: "cli_006",
    fullName: "Claire Lefèvre",
    email: "claire@designstudio.fr",
    phone: null,
    company: "Design Studio",
    tags: ["freelance"],
    createdAt: "2024-12-01",
  },
  {
    id: "cli_007",
    fullName: "Thomas Nguyen",
    email: "thomas@saaspro.io",
    phone: "+33 6 44 55 66 77",
    company: "SaaS Pro",
    tags: ["premium", "active"],
    createdAt: "2024-08-22",
  },
  {
    id: "cli_008",
    fullName: "Isabelle Moreau",
    email: null,
    phone: "+33 6 99 88 77 66",
    company: "Moreau & Associés",
    tags: ["vip"],
    createdAt: "2024-07-14",
  },
  {
    id: "cli_009",
    fullName: "Carlos Mendes",
    email: "carlos@ecommerce.pt",
    phone: "+351 912 345 678",
    company: "Ecommerce PT",
    tags: ["b2c", "trial"],
    createdAt: "2025-01-08",
  },
  {
    id: "cli_010",
    fullName: "Emma Wilson",
    email: "emma@healthtech.co",
    phone: "+44 7700 900123",
    company: "HealthTech Co",
    tags: ["b2b", "active"],
    createdAt: "2024-10-30",
  },
  {
    id: "cli_011",
    fullName: "Youssef Benali",
    email: "youssef@eduplatform.com",
    phone: null,
    company: "EduPlatform",
    tags: ["education"],
    createdAt: "2024-11-25",
  },
  {
    id: "cli_012",
    fullName: "Laura Schmidt",
    email: "laura@europe-consult.de",
    phone: "+49 151 23456789",
    company: "Europe Consult",
    tags: ["b2b", "inactive"],
    createdAt: "2024-06-19",
  },
  {
    id: "cli_013",
    fullName: "Antoine Petit",
    email: "antoine@mediahouse.fr",
    phone: "+33 6 22 11 00 99",
    company: "Media House",
    tags: ["content", "active"],
    createdAt: "2025-02-01",
  },
  {
    id: "cli_014",
    fullName: "Giulia Bianchi",
    email: null,
    phone: "+39 320 111 2233",
    company: "Bianchi Digital",
    tags: ["freelance", "trial"],
    createdAt: "2025-01-18",
  },
  {
    id: "cli_015",
    fullName: "David Cohen",
    email: "david@legaltech.io",
    phone: "+972 54 123 4567",
    company: "LegalTech.io",
    tags: ["vip", "premium"],
    createdAt: "2024-09-03",
  },
];
